plugin:
  backend: go-plugin
  go-plugin:
    folder: ../plugins/bin/
ta-store:
  backend: sql
  sql:
    driver: sqlite3
    datasource: ta-store.sql
en-store:
  backend: sql
  sql:
    driver: sqlite3
    datasource: en-store.sql
po-store:
  backend: sql
  sql:
    driver: sqlite3
    datasource: en-store.sql
po-agent:
    backend: opa
vts-grpc:
  server:
    addr: 127.0.0.1:50051
